name: LongWeekend
options:
  bundleIdPrefix: com.funzin
  deploymentTarget:
    iOS: 13.0
targets:
  LongWeekend:
    type: application
    platform: iOS
    sources: [LongWeekend]
    settings:
      base:
        INFOPLIST_FILE: LongWeekend/Resource/Info.plist
        CODE_SIGN_STYLE: Manual
    prebuildScripts:
      - name: Run SwiftGen
        script: |
                ${PODS_ROOT}/SwiftGen/bin/swiftgen
      - name: Run SwiftLint
        script: ${PODS_ROOT}/SwiftLint/swiftlint
      - name: Run LicensPlist
        script: |
                if [ $CONFIGURATION = "Debug" ]; then
                  ${PODS_ROOT}/LicensePlist/license-plist --output-path LongWeekend/Resource/Settings.bundle --prefix com.funzin.longweekend
                fi
      - name: Configure Admob
        script: |
                plistBuddy="/usr/libexec/PlistBuddy"
                Resource="${SRCROOT}/LongWeekend/Resource/"
                infoPlistFileSource="${Resoruce}/${INFOPLIST_FILE}"
                infoPlistFileDestination="${TEMP_DIR}/Preprocessed-Info.plist"
                
                envPath="${SRCROOT}/.env"
                if [ -e $envPath ]; then
                  . $envPath
                  $plistBuddy -c "Set :GADApplicationIdentifier ${GAD_APPLICATION_ID}" ${infoPlistFileDestination}
                fi
    scheme:
      gatherCoverageData: true
      testTargets:
        - LongWeekendTests
  LongWeekendTests:
    type: bundle.unit-test
    platform: iOS
    sources: [LongWeekendTests]
    dependencies:
      - target: LongWeekend
