name: LongWeekend
options:
  bundleIdPrefix: com.funzin
  minimumXcodeGenVersion: 2.23.1
  postGenCommand: make install-pod
  deploymentTarget:
    iOS: 13.0
packages:
  SwiftyUserDefaults:
    url: https://github.com/sunshinejr/SwiftyUserDefaults
    version: 5.3.0
  HolidayJp:
    url: https://github.com/funzin/holiday_jp-swift
    branch: remove-unused-date
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    version: 8.0.0
targets:
  LongWeekend:
    type: application
    platform: iOS
    sources: [LongWeekend]
    dependencies:
      - sdk: AppTrackingTransparency.framework
        weak: true
      - package: HolidayJp
      - package: SwiftyUserDefaults
      - package: Firebase
        product: FirebaseAnalytics
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.funzin.longweekend
        MARKETING_VERSION: 2.0.0
        EXCLUDED_ARCHS[sdk=iphonesimulator*]: arm64
        CURRENT_PROJECT_VERSION: 1
        VERSIONING_SYSTEM: apple-generic
        INFOPLIST_FILE: LongWeekend/Resource/Info.plist
        CODE_SIGN_STYLE: Manual
        INFOPLIST_PREPROCESS: YES
    prebuildScripts:
      - name: Run swiftformat
        script: make swiftformat
      - name: Run LicensPlist
        script: |
                if [ $CONFIGURATION = "Debug" ]; then
                  make license-plist
                fi
      - name: Configure Admob
        script: |
                plistBuddy="/usr/libexec/PlistBuddy"
                Resource="${SRCROOT}/LongWeekend/Resource/"
                infoPlistFileDestination="${TEMP_DIR}/Preprocessed-Info.plist"
                
                envPath="${SRCROOT}/.env"
                if [ -e $envPath ]; then
                  . $envPath
                  identifier=${GAD_APPLICATION_ID}
                  echo ${infoPlistFileDestination}
                  echo ${identifier}
                  $plistBuddy -c "Set :GADApplicationIdentifier ${identifier}" ${infoPlistFileDestination}
                fi
    postbuildScripts:
      - name: Run SwiftLint
        script: make swiftlint
    scheme:
      gatherCoverageData: true
      testTargets:
        - LongWeekendTests
  LongWeekendTests:
    type: bundle.unit-test
    platform: iOS
    sources: [LongWeekendTests]
    dependencies:
      - target: LongWeekend
